### ISSUE TITLE
sharing of data, dat, registry

### ISSUE THREAD

**Issue by phiweger** [viehwegerlib/zoo#7]
dat vs IPFS (think of registry)

**Comment by luizirber** [comment]
Check https://github.com/oduwsdl/ipwb for an example with IPFS, dat is already working on a registry (https://github.com/datproject/dat-registry-client)

**Comment by phiweger** [comment]
@luizirber cool, I was looking for the dat registry, thanks for the link. 

Why are you opting for IPFS instead of dat for sourmash? Like what's the features that make it more appropriate for your use cases?

**Comment by phiweger** [comment]
registry main page (https://github.com/datproject/datproject.org)

**Comment by phiweger** [comment]
https://docs.datproject.org/sleep

> SLEEP is a metadata format that allows a set of files to be accessed randomly, cryptographically verified, and dynamically updated. [...] SLEEP is designed around the concept of a register, an append only list that you can trust.

**Comment by phiweger** [comment]
> Is there an online dataset registry, like GitHub? -- [FAQ](https://docs.datproject.org/faq)

Yes. See datproject/datproject.org on GitHub.

**Comment by phiweger** [comment]
https://github.com/datproject/datproject.org/issues/458

**Comment by luizirber** [comment]
I tried to play a bit with dat (as part of https://github.com/dib-lab/sourmash/pull/166), and I think IPFS suits my needs better because it has a good-ish [Python module][0], and it exposes more options than the metaphor of 'I have a directory, I want to share it' that dat goes for (I know that internally both are very similar, but dat is harder to use because I would need to go into JS to expose what I need)

[0]: https://github.com/ipfs/py-ipfs-api

**Comment by phiweger** [comment]
I begin to feel like this too. We try to "grow" a database, and being able to only share a folder in one direction is limiting. Do you know if with IPFS two people can work on one file "together"? If so, could you point me to a source?
